name: Format

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify the code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: '--write .'
