name: Smoke Test Run

on: push

jobs:
  cypress-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/basic && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  cypress-iframes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/iframes && npm install
      - run: cd cypress/iframes && node server.js &
      - run: cd cypress/iframes && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  cypress-manual-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/manual-mode && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  cypress-multi-page:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/multi-page && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}

  playwright-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npx playwright install
      - run: cd playwright/basic && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  playwright-manual-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npx playwright install
      - run: cd playwright/manual-mode && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  playwright-typescript-multi-page:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npx playwright install
      - run: cd playwright/typescript-multi-page && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  playwright-test-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npx playwright install
      - run: cd playwright-test/basic && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  playwright-test-multi-page:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npx playwright install
      - run: cd playwright-test/multi-page && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}

  puppeteer-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd puppeteer/basic && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  puppeteer-typescript-multi-page:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd puppeteer/typescript-multi-page && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}

  wdio-test-runner-typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd wdio/test-runner/typescript && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  wdio-test-runner-typescript-multi-page:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd wdio/typescript-multi-page && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  wdio-v7-typescript-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # WDIO v7 does not work on Node > 16. Please refer to `setup.ts` for more information.
          node-version: 16
      - run: cd wdio/v7/typescript-basic && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}

  webdriverjs-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd webdriverjs/basic && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  webdriverjs-testing:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd webdriverjs/testing && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  webdriverjs-typescript-multi-page:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd webdriverjs/typescript-multi-page && npm install && npm test
        env:
          API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
