name: Smoke Test Run

on: push

jobs:
  cypress-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/basic && npm ci && npm test
  cypress-iframes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/iframes && npm ci && npm test
  cypress-manual-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/manual-mode && npm ci && npm test
  cypress-multi-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd cypress/multi-page && npm ci && npm test

  playwright-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd playwright/basic && npm ci && npm test
  playwright-manual-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd playwright/manual-mode && npm ci && npm test
  playwright-typescript-multi-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd playwright/typescript-multi-page && npm ci && npm test

  playwright-test-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd playwright-test/basic && npm ci && npm test
  playwright-test-multi-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd playwright-test/multi-page && npm ci && npm test

  puppeteer-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd puppeteer/basic && npm ci && npm test
  puppeteer-typescript-multi-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd puppeteer/typescript-multi-page && npm ci && npm test

  wdio-test-runner-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd wdio-test-runner/typescript && npm ci && npm test
  wdio-test-runner-typescript-multi-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd wdio-test-runner/typescript-multi-page && npm ci && npm test
  wdio-v7-typescript-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd wdio-v7/typescript-basic && npm ci && npm test

  webdriverjs-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd webdriverjs/basic && npm ci && npm test
  webdriverjs-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd webdriverjs/testing && npm ci && npm test
  webdriverjs-typescript-multi-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd webdriverjs/typescript-multi-page && npm ci && npm test
